iszero(succ 0);
iszero(0);
succ (pred 0);
if false then succ (succ 0) else succ 0; 
switch true case iszero(succ 0) : 1 case  true : 2 default :3;
switch succ 0 case 1 : true case  2 : false default :true;
pred true;
iszero(true);
switch 0 case true : 1 case  false : 2 default : 1;
switch succ 0 case 1 : false case  2 : 3 default :4;